In [2]:
import numpy as np

In [4]:
arr1 = np.arange(2,50,3)
arr1

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [43]:
l1 = []
l2 = []

def arr(l):
    for i in range(0,5):
        if l == 1:
            l1.append(int(input()))
        elif l == 2:
            l2.append(int(input()))
        else:
            print("Invalid list number")
        i+=1

arr(1)
arr(2)

arr1 = np.array([l1])
arr2 = np.array([l2])

arr = np.concatenate((arr1, arr2))
print("ARRAY", "\n", arr)
arr.sort()
print("SORTED ARRAY", "\n", arr)

0
9
8
7
6
5
4
3
2
1
ARRAY 
 [[0 9 8 7 6]
 [5 4 3 2 1]]
SORTED ARRAY 
 [[0 6 7 8 9]
 [1 2 3 4 5]]


In [65]:
arr = np.concatenate((arr1, arr2, arr2, arr1, arr2))
print(arr)
print("Dimension: ", arr.ndim)
print("Shape: ", arr.shape)
print("Size: ", arr.size)

[[0 9 8 7 6]
 [5 4 3 2 1]
 [5 4 3 2 1]
 [0 9 8 7 6]
 [5 4 3 2 1]]
Dimension:  2
Shape:  (5, 5)
Size:  25


In [93]:
arr3 = np.array(l1)
print(arr3.shape)

print(arr3[:, np.newaxis].shape)
print(np.expand_dims(arr3, axis=1).shape)

(5,)
(5, 1)
(5, 1)


In [113]:
arr4 = np.concatenate((arr1, arr2, arr2, arr1, arr1))
print(np.vstack((arr4.T, arr4)))
print("\n")
print(np.hstack((arr4, arr4.T)))

[[0 5 5 0 0]
 [9 4 4 9 9]
 [8 3 3 8 8]
 [7 2 2 7 7]
 [6 1 1 6 6]
 [0 9 8 7 6]
 [5 4 3 2 1]
 [5 4 3 2 1]
 [0 9 8 7 6]
 [0 9 8 7 6]]


[[0 9 8 7 6 0 5 5 0 0]
 [5 4 3 2 1 9 4 4 9 9]
 [5 4 3 2 1 8 3 3 8 8]
 [0 9 8 7 6 7 2 2 7 7]
 [0 9 8 7 6 6 1 1 6 6]]


In [117]:
np.unique(arr4, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3, 2, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64))